import React from 'react';                                                                                                                                                                                     
   import { useForm } from 'react-hook-form';                                                                                                                                                                     
   import { yupResolver } from '@hookform/resolvers/yup';                                                                                                                                                         
   import { authSchema } from '../schemas/authSchema';                                                                                                                                                            
   import InputField from './InputField';                                                                                                                                            
                                                                                                                                                                                                                  
   export default function RegisterForm() {                                                                                                                                                                       
     const {                                                                                                                                                                                                      
       register,                                                                                                                                                                                                  
       handleSubmit,                                                                                                                                                                                              
       reset,                                                                                                                                                                                                     
       formState: { errors, isSubmitting }                                                                                                                           
     } = useForm({                                                                                                                                                                                                
       resolver: yupResolver(authSchema)                                                                                                                                                                          
     });                                                                                                                                                                                                          
                                                                                                                                                                                                                  
     const onSubmit = async (data) => {                                                                                                                                                                           
       return new Promise((resolve) => {                                                                                                                                                                          
         setTimeout(() => {                                                                                                                                                                                       
           console.log("Dữ liệu gửi lên Server:", data);                                                                                                                                                          
           alert("Đăng ký thành công!");                                                                                                                                                                          
           reset();                                                                                                                                                      
           resolve();                                                                                                                                                                                             
         }, 2000);                                                                                                                                                                                                
       });                                                                                                                                                                                                        
     };                                                                                                                                                                                                           
                                                                                                                                                                                                                  
     return (                                                                                                                                                                                                     
       <div className="form-container">                                                                                                                                                                           
         <h3>Đăng ký tài khoản</h3>                                                                                                                                                                               
         <form onSubmit={handleSubmit(onSubmit)}>                                                                                                                                                                 
           <InputField                                                                                                                                                                                            
             label="Họ và tên"                                                                                                                                                                                    
             type="text"                                                                                                                                                                                          
             placeholder="Nhập họ và tên..."                                                                                                                                                                      
             error={errors.fullName}                                                                                                                                                                              
             {...register("fullName")}                                                                                                                                                                            
           />                                                                                                                                                                                                     
                                                                                                                                                                                                                  
           <InputField                                                                                                                                                                                            
             label="Email"                                                                                                                                                                                        
             type="email"                                                                                                                                                                                         
             placeholder="Nhập email..."                                                                                                                                                                          
             error={errors.email}                                                                                                                                                                                 
             {...register("email")}                                                                                                                                                                               
           />                                                                                                                                                                                                     
                                                                                                                                                                                                                  
           <InputField                                                                                                                                                                                            
             label="Mật khẩu"                                                                                                                                                                                     
             type="password"                                                                                                                                                                                      
             placeholder="Nhập mật khẩu..."                                                                                                                                                                       
             error={errors.password}                                                                                                                                                                              
             {...register("password")}                                                                                                                                                                            
           />                                                                                                                                                                                                     
                                                                                                                                                                                                                  
           <InputField                                                                                                                                                                                            
             label="Xác nhận mật khẩu"                                                                                                                                                                            
             type="password"                                                                                                                                                                                      
             placeholder="Nhập lại mật khẩu..."                                                                                                                                                                   
             error={errors.confirmPassword}                                                                                                                                                                       
             {...register("confirmPassword")}                                                                                                                                                                     
           />                                                                                                                                                                                                     
                                                                                                                                                                                                                  
           <button                                                                                                                                                                                                
             type="submit"                                                                                                                                                                                        
             className={`submit-btn ${isSubmitting ? 'loading' : ''}`}                                                                                                                                            
             disabled={isSubmitting}                                                                                                                                                                              
           >                                                                                                                                                                                                      
             {isSubmitting ? 'Đang xử lý...' : 'Đăng ký'}                                                                                                                                                         
           </button>                                                                                                                                                                                              
         </form>                                                                                                                                                                                                  
       </div>                                                                                                                                                                                                     
     );                                                                                                                                                                                                           
   } 